name: CI beta

on:
  push:
    branches:
      - openScale-3.0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "21"

      - name: Build APK
        run: ./gradlew assembleBeta

      - name: Create beta release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: beta-build
          name: openScale 3.0 beta build
          prerelease: true
          make_latest: false
          files: android_app/app/build/outputs/apk/beta/openScale-beta.apk
